name: Decrypt Credential File

on: push

jobs:
  init-job:
    name: Initial Decryption Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List Directory Structure
        run: ls -la  # Use -la to include hidden files

      - name: Print Decryption Script Contents
        run: cat ./requirements.txt

      - name: Decrypt Credentials
        run: |
          echo "Decrypting credential file..."
          chmod +x ./decrypt_sa_creds.sh
          echo "Granted Permission and Running ..."
          ./decrypt_sa_creds.sh
          echo "Decryption complete."
        env:
          SA_CREDS_PASSPHRASE: ${{ secrets.SA_CREDS_PASSPHRASE }}

      - name: Test Printing Secret (Remove in Production)
        run: |
        echo $HOME
        ls $HOME/secrets
