name: Decrypt Credential file

on: push

jobs:
  init-job:
    name: Initial Decryption job
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: List directory structure
          run: ls -la .
        - name: Show decryption content
          run: echo "Printing decryption script ...."
            cat ./decrypt_sa_creds.sh
        - run: echo "Decrypting credential file..."
            chmod +x ./decrypt_sa_creds.sh
            echo "Granted Permission and Running ...."
            ./decrypt_sa_creds.sh
            echo "Decryption complete."
          env:
            SA_CREDS_PASSPHRASE: ${{ secrets.SA_CREDS_PASSPHRASE }}
        - name: Test printing your secret (Remove this step in production)
          run: ls $HOME/secrets
