name: Decrypt Credential file

on: push

jobs:
  init-job:
    name: Initial Decryption job
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: List directory structure
          run: ls .
        - name: Show decryption content
        - run: echo "Printing decryption script ...."
        - run: cat ./requirements.txt
        - run: echo "Decrypting credential file..."
        - run: chmod +x ./decrypt_sa_creds.sh
        - run: echo "Granted Permission and Running ...."
        - run: ./decrypt_sa_creds.sh
        - run: echo "Decryption complete."
          env:
            SA_CREDS_PASSPHRASE: ${{ secrets.SA_CREDS_PASSPHRASE }}
        - name: Test printing your secret (Remove this step in production)
          run: ls $HOME/secrets
