name: Decrypt Credential file

on: push

jobs:
  init-job:
    name: Initial Decryption job
    runs-on: ubuntu-latest
    steps:
        - run: |
            set -e
            pwd
            cd ../ # Navigate to root dir x2
            cd ../
            echo "Decrypting credential file..."
            ls -a ./automl_init/automl_init
            echo "Decryption complete."
          env:
            SA_CREDS_PASSPHRASE: ${{ secrets.SA_CREDS_PASSPHRASE }}
