name: Decrypt Credential file

on: push

jobs:
  init-job:
    name: Initial Decryption job
    runs-on: ubuntu-latest
    steps:
        - run: |
            set -e
#            Navigate to root dir x2
            cd ../
            cd ../
#            echos
            echo "Decrypting credential file..."
            chmod +x ./decrypt_sa_creds.sh
            ./decrypt_sa_creds.sh
            echo "Decryption complete."
          env:
            SA_CREDS_PASSPHRASE: ${{ secrets.SA_CREDS_PASSPHRASE }}
